# Generated by Django 5.1.2 on 2024-10-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=20)),
                ("body", models.TextField(max_length=1000)),
                ("author", models.CharField(max_length=255)),
                ("img_url", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "blog_post",
                "managed": False,
            },
        ),
    ]
